version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.7-node
      # - image: php:8.1-fpm-bullseye
    steps:
      # - run: apt-get update && apt-get install -y npm
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update && sudo apt-get install -y npm nodejs
      # - run: docker-php-ext-install pdo pdo_mysql
      - restore_cache:
          key:
            v1-deps-{{ checksum "package-lock.json" }}
            # - v1-deps-
      - run: sudo npm install --location=global npm && npm i
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - run: php artisan test
      - save_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  lint_and_build:
    jobs:
      - build
